### ISSUE TITLE
Error in README.md link to openfpgaloader

### ISSUE THREAD

**Issue by SGHphoto** [benitoss/ColorLight_FPGA_boards#1]
There seems to be a typo in he instructions that links to the openfpgaloader.zip

APIO

In the folder -> C:\Users\your_user.icestudio\apio\packages
Add the files of toolchain-opefpgaload.zip file

it links to
https://github.com/benitoss/ColorLight_FPGA_boards/raw/main/Icestudio_update_boards/toolchain-opefpgaload.zip

But should link to

https://github.com/benitoss/ColorLight_FPGA_boards/blob/main/Icestudio_update_boards/toolchain-openfpgaloader.zip

**Comment by benitoss** [comment]
It is already fixed. 
Thanks for let me know it.
