### ISSUE TITLE
J4 R1 not defined

### ISSUE THREAD

**Issue by stanleyseow** [benitoss/ColorLight_FPGA_boards#3]
Firstly, thanks for adding ColerLight to Ice Studio. Great work.

I would like to report J4 R1 was not configured.

according to chubby75, J4 R1 should be M9

thanks

**Comment by benitoss** [comment]
The ColorLight-5A-75B has 3 versions (6.1 , 7 and 8)
and the ColorLight-5A-75E has 2 versions (6 and 7.1)
What version of Colorlight board are you using ???

**Comment by stanleyseow** [comment]
The ColorLight-5A-75B  versions  7.0

**Comment by benitoss** [comment]
For the ColorLight-5A-75B versions 7.0   the pinout is here https://github.com/q3k/chubby75/blob/master/5a-75b/hardware_V7.0.md   and JR_R1 is M9 as you say
In the pinout is defined  here
{"type":"inout","name":"J4_R1","value":"M9","pullmode":"NONE"},

But if you use the J4_R1 you will get this error
ERROR: IO pin 'vf69136$tr_io' constrained to pin 'M9', which does not exist for package 'CABGA256'.

So, I have tried to use the M9 pin in Lattice Diamond IDE and It was working
Maybe I think it is an error of the ECP5-toolchain.
So by now, it is convenient don't use the J4_R1 signal

**Comment by stanleyseow** [comment]
Ok
